# Generated by Django 4.1.1 on 2022-10-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_company_address_remove_company_geolocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(default=0, help_text='В google maps найти вашу компанию и вставить src ссылку', max_length=1000),
            preserve_default=False,
        ),
    ]
